apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-k8sexec-inventory-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8sexec-inventory-role
subjects:
  - name: k8sexec
    kind: User
    apiGroup: rbac.authorization.k8s.io

